### ISSUE TITLE
Not Enough Training Data

### ISSUE THREAD

**Issue by lucasrpatten** [lucasrpatten/RegexGenerator#3]
We need to add a few thousand more examples to the training data for accuracy to be at a reasonable level.

**Comment by astarivi** [comment]
Can do. Are there any constraints or recommendations I should be aware of while building the dataset?

**Comment by lucasrpatten** [comment]
For version 1 of the model, the input is in the format (list[Texts that should match], list[Texts that shouldn't match]), and the output is the predicted regex pattern. Keep the input list lengths to a reasonable size, say, 10 or 20 max with 100 or 200 max characters each - no one's gonna need to be inputting 100 texts that match or whatever. So just keep these lengths reasonable, there's no real limit, but not excessive.

Additionally, the output regex should be the regex that makes the most sense for the given texts. There will always be multiple regexes that match, but some just make more sense than others.

Thanks a ton. In the future i hope to add more optional data inputs, like parts of known regex, known regex length, etc., So you could add a column for this in the db if you really wanted, but don't worry about it much.

I'll be updating the readme tomorrow to be more complete with future plans like this and some other information.
