### ISSUE TITLE
Is generated Regex available？

### ISSUE THREAD

**Issue by foreversolar** [lucasrpatten/RegexGenerator#7]
Hi， I greatly appreciate your work, and I am also interested in this topic. 
After I ran your code, I found the generated text is : ['Y', 'O', 'I', 'D', 'E', 'G', 'M', 'M', 'F', 'E', 'C', 'B', '<', '<', '6', '/', '0', '&', '#', '$', '\x1f', '\x1f', '\x19', '\x17', '\x15', '\x15', '\x18', '\x16', '\x11', '\x12', '\x10', '\x10', '\x10', '\x0e', '\r', '\x0b', '\x0e', '\x07', '\t', '\x0b', '\x0b', '\x0c', '\x06', '\t', '\n', '\x0c', '\x06', '\t', '\x05', '\x04']

I think this may not be an available legal regex.  I want to know if you can get a working regex by your data and model for now. If not, is there any improvement needed?

**Comment by lucasrpatten** [comment]
This is just a simple idea I had and I was gonna try to design to learn more about generative AI. I will at some point come back and probably restart this project, but it is not currently functional. I've been busy with university, but I'll get to it at some point.

**Comment by foreversolar** [comment]
Thank you very much for your reply. I have the same idea to integrate generative AI with this project. Looking forward to your coming back and I would like to contribute if I made some progress.
